config/routes.rb
Rails.application.routes.draw do

    root 'api/v1/recipes#index'

    namespace :api do
      namespace :v1 do
        resources :recipes, only: [:index, :show]
        resources :categories, only: [:index, :show]
        # resources :recipes
        # resources only: [:create, :destroy]
        # resources :categories
        # resources only: [:create, :destroy]
      end
    end

    resources :recipes, only: [:new, :create, :destroy]
    get "/recipes/home", to: "recipes#home"

    # get "/recipes/new", to: "recipes#new"

    resources :users, only: [:create, :show]
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    get "/logout", to: "sessions#destroy"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    serialize :ingredients, Array
    belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    validates :username, presence: true, uniqueness: true
    validates :password, presence: true
end

app/controllers/api/v1/categories_controller.rb
module Api
    module V1
        class CategoriesController < ApplicationController

            skip_before_action :verify_authenticity_token
            protect_from_forgery with: :null_session

            def index
                categories = Category.all
                render json: CategorySerializer.new(categories).serialized_json
            end

            def show
                category = Category.find_by(id: params[:id])
                render json: CategorySerializer.new(category).serialized_json
            end

            def create
                category = Category.new(category_params)

                if category.save
                    render json: CategorySerializer.new(category).serialized_json
                else
                    render json: { error: recipe.errors.messages }, status: 422
                end
            end

            def update
                category = Category.find_by(id: params[:id])

                if category.update(category_params)
                    render json: CategorySerializer.new(category).serialized_json
                else
                    render json: { error: recipe.errors.messages }, status: 422
                end
            end

            def destroy
                category = Category.find_by(id: params[:id])

                if category.destroy
                    head :no_content
                else
                    render json: { error: category.errors.messages }, status: 422
                end
            end

            private

            def category_params
                params.require(:category).permit(:name)
            end

            def options
                @options ||= { include: %i[recipes] }
            end

        end
    end
end

app/controllers/api/v1/recipes_controller.rb
module Api
    module V1
        class RecipesController < ApplicationController

            skip_before_action :verify_authenticity_token
            protect_from_forgery with: :null_session

            def index
                recipes = Recipe.all
                render json: RecipeSerializer.new(recipes).serialized_json
            end

            def show
                recipe = Recipe.find_by(id: params[:id])
                render json: RecipeSerializer.new(recipe).serialized_json
            end

        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?


    private

    def current_user
        @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!session[:user_id]
    end

    def redirect_if_not_logged_in
        redirect_to '/login' if !logged_in?
    end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

    before_action :redirect_if_not_logged_in

    def home
        @user = current_user
        @recipes = Recipe.all
    end

    def new
        @recipe = Recipe.new
        @categories = Category.all
    end

    def create
        @recipe = Recipe.create(
            name: recipe_params[:name],
            ingredients: recipe_params[:ingredients].split(", "),
            image_url: recipe_params[:image_url],
            category_id: recipe_params[:category_id]
        )
        if @recipe.save
            redirect_to '/recipes/home'
        else
            redirect_to '/recipes/new'
        end
    end

    def update
    end


    def destroy
        @recipe = Recipe.find_by_id(params[:id])
        @recipe.destroy
        redirect_to '/recipes/home'
    end

    private

    def recipe_params
        params[:recipe]
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def create
        user = User.find_by(username: params[:user][:username])
        if user && user.authenticate(params[:user][:password])
            session[:user_id] = user.id
            redirect_to "/recipes/home"
        else
            flash[:message] = "Incorrect login information, please try again."
            redirect_to "/login"
        end
    end

    def destroy
        session.clear
        redirect_to "/login"
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    skip_before_action :verify_authenticity_token
    protect_from_forgery with: :null_session

    def new
        @user = User.new
    end

    def create
        @user = User.create(user_params)
        if @user.save
            render json: { user: @user }
        else
            render json: { error: "Not a valid user" }
        end
    end

    def show
        @user = User.find_by(id: params[:id])

        render json: { user: @user }
    end

    private

    def user_params
        params.require(:user).permit(:username, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%# <title>KetoIsNeatoBackend</title> %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "home", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if logged_in? %>
      <div class="navbar">
        <div class="navbar-title-container">
          <h1>Keto is Neato Backend</h1>
        </div>
        <div class="navbar-actions-container">
          <%= link_to "Home", '/recipes/home' %>
          <%= link_to "New Recipe", new_recipe_path%>
          <%= link_to "Logout", logout_path, method:"delete"%>
        </div>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/recipes/home.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Keto is Neato</title>
</head>
<body>
    
    <h1>Welcome, <%= @user.username %>!</h1>

    <div class="all-recipes-container">
        <% @recipes.each do |r| %>
            <div class="recipe-card">
                <div class="recipe-image-container">
                    <img class="recipe-image" src=<%= r.image_url %>>
                </div>
                <div>
                    <div class="recipe-content">
                        <h2 class="recipe-title"><%=r.name%></h2>
                        <ul>
                            <% r.ingredients.each do |i| %>
                                <li><%=i%></li>
                            <% end %>
                        </ul>
                    </div>
                </div>
                <div class="recipe-delete-button-container">
                    <%= button_to "Delete", "/recipes/#{r.id}", method: :delete %>
                </div>
            </div>
        <% end %>
    </div>
</body>
</html>

app/views/recipes/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>New Recipe</title>
</head>
<body>
    
    <h1>New Recipe</h1>

    <%= form_for(@recipe) do |r|%>

        <%= r.label :name, "Recipe Name" %><br>
        <%= r.text_field :name %>
        <br><br>
        <%= r.label :ingredients, "List the ingredients for this Recipe" %><br>
        <%= r.text_field :ingredients, :placeholder => "milk, eggs, sugar..." %>
        <br><br>
        <%= r.label :image_url, "Add a link to the picture for this recipe" %><br>
        <%= r.text_field :image_url %>
        <br><br>
        <%= r.label :category_id, "What category does this Recipe belong to?" %>
        <%= r.collection_select :category_id, @categories, :id, :name, prompt: true %>
        <br><br>
        <%= r.submit %>

    <% end %>
    
</body>
</html>